# generated by datamodel-codegen:
#   filename:  sonic-port.yaml
#   timestamp: 2024-05-14T11:03:03+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class SonicPortSonicPortPortPortListIndex(BaseModel):
    sonic_port_index: Optional[int] = Field(None, alias='sonic-port:index')


class PutSonicPortSonicPortPortPortListIndex(SonicPortSonicPortPortPortListIndex):
    pass


class PatchSonicPortSonicPortPortPortListIndex(SonicPortSonicPortPortPortListIndex):
    pass


class GetSonicPortSonicPortPortPortListIndex(BaseModel):
    sonic_port_index: Optional[int] = Field(None, alias='sonic-port:index')


class SonicPortSonicPortPortPortListParentPort(BaseModel):
    sonic_port_parent_port: Optional[str] = Field(None, alias='sonic-port:parent_port')


class PutSonicPortSonicPortPortPortListParentPort(
    SonicPortSonicPortPortPortListParentPort
):
    pass


class PatchSonicPortSonicPortPortPortListParentPort(
    SonicPortSonicPortPortPortListParentPort
):
    pass


class GetSonicPortSonicPortPortPortListParentPort(BaseModel):
    sonic_port_parent_port: Optional[str] = Field(None, alias='sonic-port:parent_port')


class SonicPortSonicPortPortPortListSpeed(BaseModel):
    sonic_port_speed: Optional[int] = Field(None, alias='sonic-port:speed')


class PutSonicPortSonicPortPortPortListSpeed(SonicPortSonicPortPortPortListSpeed):
    pass


class PatchSonicPortSonicPortPortPortListSpeed(SonicPortSonicPortPortPortListSpeed):
    pass


class GetSonicPortSonicPortPortPortListSpeed(BaseModel):
    sonic_port_speed: Optional[int] = Field(None, alias='sonic-port:speed')


class SonicPortSonicPortPortPortListValidSpeeds(BaseModel):
    sonic_port_valid_speeds: Optional[str] = Field(
        None, alias='sonic-port:valid_speeds'
    )


class PutSonicPortSonicPortPortPortListValidSpeeds(
    SonicPortSonicPortPortPortListValidSpeeds
):
    pass


class PatchSonicPortSonicPortPortPortListValidSpeeds(
    SonicPortSonicPortPortPortListValidSpeeds
):
    pass


class GetSonicPortSonicPortPortPortListValidSpeeds(BaseModel):
    sonic_port_valid_speeds: Optional[str] = Field(
        None, alias='sonic-port:valid_speeds'
    )


class SonicPortSonicPortPortPortListAlias(BaseModel):
    sonic_port_alias: Optional[str] = Field(None, alias='sonic-port:alias')


class PutSonicPortSonicPortPortPortListAlias(SonicPortSonicPortPortPortListAlias):
    pass


class PatchSonicPortSonicPortPortPortListAlias(SonicPortSonicPortPortPortListAlias):
    pass


class GetSonicPortSonicPortPortPortListAlias(BaseModel):
    sonic_port_alias: Optional[str] = Field(None, alias='sonic-port:alias')


class SonicPortSonicPortPortPortListDescription(BaseModel):
    sonic_port_description: Optional[str] = Field(None, alias='sonic-port:description')


class PutSonicPortSonicPortPortPortListDescription(
    SonicPortSonicPortPortPortListDescription
):
    pass


class PatchSonicPortSonicPortPortPortListDescription(
    SonicPortSonicPortPortPortListDescription
):
    pass


class GetSonicPortSonicPortPortPortListDescription(BaseModel):
    sonic_port_description: Optional[str] = Field(None, alias='sonic-port:description')


class SonicPortSonicPortPortPortListMtu(BaseModel):
    sonic_port_mtu: Optional[int] = Field(None, alias='sonic-port:mtu')


class PutSonicPortSonicPortPortPortListMtu(SonicPortSonicPortPortPortListMtu):
    pass


class PatchSonicPortSonicPortPortPortListMtu(SonicPortSonicPortPortPortListMtu):
    pass


class GetSonicPortSonicPortPortPortListMtu(BaseModel):
    sonic_port_mtu: Optional[int] = Field(None, alias='sonic-port:mtu')


class SonicPortSonicPortPortPortListLanes(BaseModel):
    sonic_port_lanes: Optional[str] = Field(None, alias='sonic-port:lanes')


class PutSonicPortSonicPortPortPortListLanes(SonicPortSonicPortPortPortListLanes):
    pass


class PatchSonicPortSonicPortPortPortListLanes(SonicPortSonicPortPortPortListLanes):
    pass


class GetSonicPortSonicPortPortPortListLanes(BaseModel):
    sonic_port_lanes: Optional[str] = Field(None, alias='sonic-port:lanes')


class SonicPortAdminStatus(Enum):
    up = 'up'
    down = 'down'


class SonicPortSonicPortPortPortListAdminStatus(BaseModel):
    sonic_port_admin_status: Optional[SonicPortAdminStatus] = Field(
        None, alias='sonic-port:admin_status'
    )


class PutSonicPortSonicPortPortPortListAdminStatus(
    SonicPortSonicPortPortPortListAdminStatus
):
    pass


class PatchSonicPortSonicPortPortPortListAdminStatus(
    SonicPortSonicPortPortPortListAdminStatus
):
    pass


class GetSonicPortSonicPortPortPortListAdminStatus(BaseModel):
    sonic_port_admin_status: Optional[SonicPortAdminStatus] = Field(
        None, alias='sonic-port:admin_status'
    )


class SonicPortAutoneg(Enum):
    on = 'on'
    off = 'off'


class SonicPortSonicPortPortPortListAutoneg(BaseModel):
    sonic_port_autoneg: Optional[SonicPortAutoneg] = Field(
        None, alias='sonic-port:autoneg'
    )


class PutSonicPortSonicPortPortPortListAutoneg(SonicPortSonicPortPortPortListAutoneg):
    pass


class PatchSonicPortSonicPortPortPortListAutoneg(SonicPortSonicPortPortPortListAutoneg):
    pass


class GetSonicPortSonicPortPortPortListAutoneg(BaseModel):
    sonic_port_autoneg: Optional[SonicPortAutoneg] = Field(
        None, alias='sonic-port:autoneg'
    )


class SonicPortSonicPortPortPortListFec(BaseModel):
    sonic_port_fec: Optional[str] = Field(None, alias='sonic-port:fec')


class PutSonicPortSonicPortPortPortListFec(SonicPortSonicPortPortPortListFec):
    pass


class PatchSonicPortSonicPortPortPortListFec(SonicPortSonicPortPortPortListFec):
    pass


class GetSonicPortSonicPortPortPortListFec(BaseModel):
    sonic_port_fec: Optional[str] = Field(None, alias='sonic-port:fec')


class SonicPortSonicPortPortPortListPfcAsym(BaseModel):
    sonic_port_pfc_asym: Optional[str] = Field(None, alias='sonic-port:pfc_asym')


class PutSonicPortSonicPortPortPortListPfcAsym(SonicPortSonicPortPortPortListPfcAsym):
    pass


class PatchSonicPortSonicPortPortPortListPfcAsym(SonicPortSonicPortPortPortListPfcAsym):
    pass


class GetSonicPortSonicPortPortPortListPfcAsym(BaseModel):
    sonic_port_pfc_asym: Optional[str] = Field(None, alias='sonic-port:pfc_asym')


class SonicPortSonicPortPortPortListTpid(BaseModel):
    sonic_port_tpid: Optional[str] = Field(None, alias='sonic-port:tpid')


class PutSonicPortSonicPortPortPortListTpid(SonicPortSonicPortPortPortListTpid):
    pass


class PatchSonicPortSonicPortPortPortListTpid(SonicPortSonicPortPortPortListTpid):
    pass


class GetSonicPortSonicPortPortPortListTpid(BaseModel):
    sonic_port_tpid: Optional[str] = Field(None, alias='sonic-port:tpid')


class SonicPortSonicPortPortPortListMuxCable(BaseModel):
    sonic_port_mux_cable: Optional[bool] = Field(None, alias='sonic-port:mux_cable')


class PutSonicPortSonicPortPortPortListMuxCable(SonicPortSonicPortPortPortListMuxCable):
    pass


class PatchSonicPortSonicPortPortPortListMuxCable(
    SonicPortSonicPortPortPortListMuxCable
):
    pass


class GetSonicPortSonicPortPortPortListMuxCable(BaseModel):
    sonic_port_mux_cable: Optional[bool] = Field(None, alias='sonic-port:mux_cable')


class SonicPortSonicPortPortPortListTxPower(BaseModel):
    sonic_port_tx_power: Optional[float] = Field(None, alias='sonic-port:tx_power')


class PutSonicPortSonicPortPortPortListTxPower(SonicPortSonicPortPortPortListTxPower):
    pass


class PatchSonicPortSonicPortPortPortListTxPower(SonicPortSonicPortPortPortListTxPower):
    pass


class GetSonicPortSonicPortPortPortListTxPower(BaseModel):
    sonic_port_tx_power: Optional[float] = Field(None, alias='sonic-port:tx_power')


class SonicPortSonicPortPortPortListLaserFreq(BaseModel):
    sonic_port_laser_freq: Optional[int] = Field(None, alias='sonic-port:laser_freq')


class PutSonicPortSonicPortPortPortListLaserFreq(
    SonicPortSonicPortPortPortListLaserFreq
):
    pass


class PatchSonicPortSonicPortPortPortListLaserFreq(
    SonicPortSonicPortPortPortListLaserFreq
):
    pass


class GetSonicPortSonicPortPortPortListLaserFreq(BaseModel):
    sonic_port_laser_freq: Optional[int] = Field(None, alias='sonic-port:laser_freq')


class SonicPortSonicPortPortPortListGridSpace(BaseModel):
    sonic_port_grid_space: Optional[int] = Field(None, alias='sonic-port:grid_space')


class PutSonicPortSonicPortPortPortListGridSpace(
    SonicPortSonicPortPortPortListGridSpace
):
    pass


class PatchSonicPortSonicPortPortPortListGridSpace(
    SonicPortSonicPortPortPortListGridSpace
):
    pass


class GetSonicPortSonicPortPortPortListGridSpace(BaseModel):
    sonic_port_grid_space: Optional[int] = Field(None, alias='sonic-port:grid_space')


class SonicPortSonicPortPortPortListApplicationCode(BaseModel):
    sonic_port_application_code: Optional[str] = Field(
        None, alias='sonic-port:application_code'
    )


class PutSonicPortSonicPortPortPortListApplicationCode(
    SonicPortSonicPortPortPortListApplicationCode
):
    pass


class PatchSonicPortSonicPortPortPortListApplicationCode(
    SonicPortSonicPortPortPortListApplicationCode
):
    pass


class GetSonicPortSonicPortPortPortListApplicationCode(BaseModel):
    sonic_port_application_code: Optional[str] = Field(
        None, alias='sonic-port:application_code'
    )


class SonicPortSonicPortPortPortListPmsEnable(BaseModel):
    sonic_port_pms_enable: Optional[str] = Field(None, alias='sonic-port:pms_enable')


class PutSonicPortSonicPortPortPortListPmsEnable(
    SonicPortSonicPortPortPortListPmsEnable
):
    pass


class PatchSonicPortSonicPortPortPortListPmsEnable(
    SonicPortSonicPortPortPortListPmsEnable
):
    pass


class GetSonicPortSonicPortPortPortListPmsEnable(BaseModel):
    sonic_port_pms_enable: Optional[str] = Field(None, alias='sonic-port:pms_enable')


class SonicPortSonicPortPortPortListPmsMaximum(BaseModel):
    sonic_port_pms_maximum: Optional[int] = Field(None, alias='sonic-port:pms_maximum')


class PutSonicPortSonicPortPortPortListPmsMaximum(
    SonicPortSonicPortPortPortListPmsMaximum
):
    pass


class PatchSonicPortSonicPortPortPortListPmsMaximum(
    SonicPortSonicPortPortPortListPmsMaximum
):
    pass


class GetSonicPortSonicPortPortPortListPmsMaximum(BaseModel):
    sonic_port_pms_maximum: Optional[int] = Field(None, alias='sonic-port:pms_maximum')


class SonicPortSonicPortPortPortListPmsViolation(BaseModel):
    sonic_port_pms_violation: Optional[str] = Field(
        None, alias='sonic-port:pms_violation'
    )


class PutSonicPortSonicPortPortPortListPmsViolation(
    SonicPortSonicPortPortPortListPmsViolation
):
    pass


class PatchSonicPortSonicPortPortPortListPmsViolation(
    SonicPortSonicPortPortPortListPmsViolation
):
    pass


class GetSonicPortSonicPortPortPortListPmsViolation(BaseModel):
    sonic_port_pms_violation: Optional[str] = Field(
        None, alias='sonic-port:pms_violation'
    )


class AdminStatus(Enum):
    up = 'up'
    down = 'down'


class Autoneg(Enum):
    on = 'on'
    off = 'off'


class SonicPortSonicPortSonicportsonicportPORTPORTLIST(BaseModel):
    ifname: str
    index: Optional[int] = None
    parent_port: Optional[str] = None
    speed: Optional[int] = None
    valid_speeds: Optional[str] = None
    alias: Optional[str] = None
    description: Optional[str] = None
    mtu: Optional[int] = None
    lanes: Optional[str] = None
    admin_status: Optional[AdminStatus] = None
    autoneg: Optional[Autoneg] = None
    fec: Optional[str] = None
    pfc_asym: Optional[str] = None
    tpid: Optional[str] = None
    mux_cable: Optional[bool] = None
    tx_power: Optional[float] = None
    laser_freq: Optional[int] = None
    grid_space: Optional[int] = None
    application_code: Optional[str] = None
    pms_enable: Optional[str] = None
    pms_maximum: Optional[int] = None
    pms_violation: Optional[str] = None


class SonicPortSonicPortSonicportsonicportPORT(BaseModel):
    PORT_LIST: List[SonicPortSonicPortSonicportsonicportPORTPORTLIST] = []


class SonicPortSonicPortSonicportsonicport(BaseModel):
    PORT: SonicPortSonicPortSonicportsonicportPORT = SonicPortSonicPortSonicportsonicportPORT()


class SonicPortSonicPort(BaseModel):
    sonic_port_sonic_port: SonicPortSonicPortSonicportsonicport = Field(
        SonicPortSonicPortSonicportsonicport(), alias='sonic-port:sonic-port'
    )


class PostSonicPortSonicPort(SonicPortSonicPort):
    pass


class PutSonicPortSonicPort(SonicPortSonicPort):
    pass


class PatchSonicPortSonicPort(SonicPortSonicPort):
    pass


class GetSonicPortSonicPort(BaseModel):
    sonic_port_sonic_port: Optional[SonicPortSonicPortSonicportsonicport] = Field(
        SonicPortSonicPortSonicportsonicport(), alias='sonic-port:sonic-port'
    )


class SonicPortSonicPortPort(BaseModel):
    sonic_port_PORT: Optional[SonicPortSonicPortSonicportsonicportPORT] = Field(
        None, alias='sonic-port:PORT'
    )


class PostSonicPortSonicPortPort(SonicPortSonicPortPort):
    pass


class PutSonicPortSonicPortPort(SonicPortSonicPortPort):
    pass


class PatchSonicPortSonicPortPort(SonicPortSonicPortPort):
    pass


class GetSonicPortSonicPortPort(BaseModel):
    sonic_port_PORT: Optional[SonicPortSonicPortSonicportsonicportPORT] = Field(
        None, alias='sonic-port:PORT'
    )


class SonicPortSonicPortPortPortList(BaseModel):
    sonic_port_PORT_LIST: Optional[
        List[SonicPortSonicPortSonicportsonicportPORTPORTLIST]
    ] = Field(None, alias='sonic-port:PORT_LIST')


class PutSonicPortSonicPortPortPortList(SonicPortSonicPortPortPortList):
    pass


class PatchSonicPortSonicPortPortPortList(SonicPortSonicPortPortPortList):
    pass


class GetSonicPortSonicPortPortPortList(BaseModel):
    sonic_port_PORT_LIST: Optional[
        List[SonicPortSonicPortSonicportsonicportPORTPORTLIST]
    ] = Field(None, alias='sonic-port:PORT_LIST')


class PostListSonicPortSonicPortPortPortList(SonicPortSonicPortPortPortList):
    pass


class PutListSonicPortSonicPortPortPortList(SonicPortSonicPortPortPortList):
    pass


class PatchListSonicPortSonicPortPortPortList(SonicPortSonicPortPortPortList):
    pass


class PostSonicPortSonicPortPortPortListIndex(
    SonicPortSonicPortPortPortListIndex,
    SonicPortSonicPortPortPortListParentPort,
    SonicPortSonicPortPortPortListSpeed,
    SonicPortSonicPortPortPortListValidSpeeds,
    SonicPortSonicPortPortPortListAlias,
    SonicPortSonicPortPortPortListDescription,
    SonicPortSonicPortPortPortListMtu,
    SonicPortSonicPortPortPortListLanes,
    SonicPortSonicPortPortPortListAdminStatus,
    SonicPortSonicPortPortPortListAutoneg,
    SonicPortSonicPortPortPortListFec,
    SonicPortSonicPortPortPortListPfcAsym,
    SonicPortSonicPortPortPortListTpid,
    SonicPortSonicPortPortPortListMuxCable,
    SonicPortSonicPortPortPortListTxPower,
    SonicPortSonicPortPortPortListLaserFreq,
    SonicPortSonicPortPortPortListGridSpace,
    SonicPortSonicPortPortPortListApplicationCode,
    SonicPortSonicPortPortPortListPmsEnable,
    SonicPortSonicPortPortPortListPmsMaximum,
    SonicPortSonicPortPortPortListPmsViolation,
):
    pass
