# generated by datamodel-codegen:
#   filename:  sonic_vlan.yaml
#   timestamp: 2024-05-14T13:24:20+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class SonicVlanSonicVlanVlanVlanListVlanid(BaseModel):
    sonic_vlan_vlanid: Optional[int] = Field(None, alias='sonic-vlan:vlanid')


class PutSonicVlanSonicVlanVlanVlanListVlanid(SonicVlanSonicVlanVlanVlanListVlanid):
    pass


class PatchSonicVlanSonicVlanVlanVlanListVlanid(SonicVlanSonicVlanVlanVlanListVlanid):
    pass


class GetSonicVlanSonicVlanVlanVlanListVlanid(BaseModel):
    sonic_vlan_vlanid: Optional[int] = Field(None, alias='sonic-vlan:vlanid')


class SonicVlanSonicVlanVlanVlanListMembers(BaseModel):
    sonic_vlan_members: Optional[List[str]] = Field(None, alias='sonic-vlan:members')


class PutSonicVlanSonicVlanVlanVlanListMembers(SonicVlanSonicVlanVlanVlanListMembers):
    pass


class PatchSonicVlanSonicVlanVlanVlanListMembers(SonicVlanSonicVlanVlanVlanListMembers):
    pass


class GetSonicVlanSonicVlanVlanVlanListMembers(BaseModel):
    sonic_vlan_members: Optional[List[str]] = Field(None, alias='sonic-vlan:members')


class SonicVlanSonicVlanVlanVlanListDhcpServers(BaseModel):
    sonic_vlan_dhcp_servers: List[str] = Field(
        [], alias='sonic-vlan:dhcp_servers'
    )


class PutSonicVlanSonicVlanVlanVlanListDhcpServers(
    SonicVlanSonicVlanVlanVlanListDhcpServers
):
    pass


class PatchSonicVlanSonicVlanVlanVlanListDhcpServers(
    SonicVlanSonicVlanVlanVlanListDhcpServers
):
    pass


class GetSonicVlanSonicVlanVlanVlanListDhcpServers(BaseModel):
    sonic_vlan_dhcp_servers: Optional[List[str]] = Field(
        None, alias='sonic-vlan:dhcp_servers'
    )


class SonicVlanSonicVlanVlanVlanListMtu(BaseModel):
    sonic_vlan_mtu: Optional[int] = Field(None, alias='sonic-vlan:mtu')


class PutSonicVlanSonicVlanVlanVlanListMtu(SonicVlanSonicVlanVlanVlanListMtu):
    pass


class PatchSonicVlanSonicVlanVlanVlanListMtu(SonicVlanSonicVlanVlanVlanListMtu):
    pass


class GetSonicVlanSonicVlanVlanVlanListMtu(BaseModel):
    sonic_vlan_mtu: Optional[int] = Field(None, alias='sonic-vlan:mtu')


class SonicVlanAdminStatus(Enum):
    up = 'up'
    down = 'down'


class SonicVlanSonicVlanVlanVlanListAdminStatus(BaseModel):
    sonic_vlan_admin_status: Optional[SonicVlanAdminStatus] = Field(
        None, alias='sonic-vlan:admin_status'
    )


class PutSonicVlanSonicVlanVlanVlanListAdminStatus(
    SonicVlanSonicVlanVlanVlanListAdminStatus
):
    pass


class PatchSonicVlanSonicVlanVlanVlanListAdminStatus(
    SonicVlanSonicVlanVlanVlanListAdminStatus
):
    pass


class GetSonicVlanSonicVlanVlanVlanListAdminStatus(BaseModel):
    sonic_vlan_admin_status: Optional[SonicVlanAdminStatus] = Field(
        None, alias='sonic-vlan:admin_status'
    )


class SonicVlanTaggingMode(Enum):
    untagged = 'untagged'
    tagged = 'tagged'
    priority_tagged = 'priority_tagged'


class SonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode(BaseModel):
    sonic_vlan_tagging_mode: Optional[SonicVlanTaggingMode] = Field(
        None, alias='sonic-vlan:tagging_mode'
    )


class PostSonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode(
    SonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode
):
    pass


class PutSonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode(
    SonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode
):
    pass


class PatchSonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode(
    SonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode
):
    pass


class GetSonicVlanSonicVlanVlanMemberVlanMemberListTaggingMode(BaseModel):
    sonic_vlan_tagging_mode: Optional[SonicVlanTaggingMode] = Field(
        None, alias='sonic-vlan:tagging_mode'
    )


class GetSonicVlanSonicVlanVlanTableVlanTableListAdminStatus(BaseModel):
    sonic_vlan_admin_status: Optional[SonicVlanAdminStatus] = Field(
        None, alias='sonic-vlan:admin_status'
    )


class GetSonicVlanSonicVlanVlanTableVlanTableListMtu(BaseModel):
    sonic_vlan_mtu: Optional[int] = Field(None, alias='sonic-vlan:mtu')


class SonicVlanOperStatus(Enum):
    up = 'up'
    down = 'down'


class GetSonicVlanSonicVlanVlanTableVlanTableListOperStatus(BaseModel):
    sonic_vlan_oper_status: Optional[SonicVlanOperStatus] = Field(
        None, alias='sonic-vlan:oper_status'
    )


class GetSonicVlanSonicVlanVlanMemberTableVlanMemberTableListTaggingMode(BaseModel):
    sonic_vlan_tagging_mode: Optional[SonicVlanTaggingMode] = Field(
        None, alias='sonic-vlan:tagging_mode'
    )


class AdminStatus(Enum):
    up = 'up'
    down = 'down'


class SonicVlanListItem(BaseModel):
    name: str
    vlanid: Optional[int] = None
    members: Optional[List[str]] = None
    dhcp_servers: Optional[List[str]] = None
    mtu: Optional[int] = None
    admin_status: Optional[AdminStatus] = None


class SonicVlanSonicVlanSonicvlansonicvlanVLAN(BaseModel):
    VLAN_LIST: List[SonicVlanListItem] = []


class TaggingMode(Enum):
    untagged = 'untagged'
    tagged = 'tagged'
    priority_tagged = 'priority_tagged'


class SonicVlanMemberListItem(BaseModel):
    name: str
    ifname: str
    tagging_mode: Optional[TaggingMode] = None


class SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER(BaseModel):
    VLAN_MEMBER_LIST: List[SonicVlanMemberListItem] = []


class SonicVlanSonicVlanSonicvlansonicvlan(BaseModel):
    VLAN: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLAN] = SonicVlanSonicVlanSonicvlansonicvlanVLAN()
    VLAN_MEMBER: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER] = \
        SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER()


class OperStatus(Enum):
    up = 'up'
    down = 'down'


class GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLEVLANTABLELIST(BaseModel):
    name: str
    admin_status: Optional[AdminStatus] = None
    mtu: Optional[int] = None
    oper_status: Optional[OperStatus] = None


class GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLE(BaseModel):
    VLAN_TABLE_LIST: Optional[
        List[GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLEVLANTABLELIST]
    ] = None


class GetSonicVlanSonicVlanSonicvlansonicvlanVLANMEMBERTABLE(BaseModel):
    VLAN_MEMBER_TABLE_LIST: Optional[
        List[SonicVlanMemberListItem]
    ] = None


class GetSonicVlanSonicVlanSonicvlansonicvlan(BaseModel):
    VLAN: SonicVlanSonicVlanSonicvlansonicvlanVLAN = SonicVlanSonicVlanSonicvlansonicvlanVLAN()
    VLAN_MEMBER: SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER = SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER()
    VLAN_TABLE: GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLE = GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLE()
    VLAN_MEMBER_TABLE: GetSonicVlanSonicVlanSonicvlansonicvlanVLANMEMBERTABLE = \
        GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLE()


class SonicVlanSonicVlan(BaseModel):
    sonic_vlan_sonic_vlan: SonicVlanSonicVlanSonicvlansonicvlan = Field(
        SonicVlanSonicVlanSonicvlansonicvlan(), alias='sonic-vlan:sonic-vlan'
    )


class PostSonicVlanSonicVlan(SonicVlanSonicVlan):
    pass


class PutSonicVlanSonicVlan(SonicVlanSonicVlan):
    pass


class PatchSonicVlanSonicVlan(SonicVlanSonicVlan):
    pass


class GetSonicVlanSonicVlan(BaseModel):
    sonic_vlan_sonic_vlan: Optional[GetSonicVlanSonicVlanSonicvlansonicvlan] = Field(
        None, alias='sonic-vlan:sonic-vlan'
    )


class SonicVlanSonicVlanVlan(BaseModel):
    sonic_vlan_VLAN: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLAN] = Field(
        None, alias='sonic-vlan:VLAN'
    )


class PutSonicVlanSonicVlanVlan(SonicVlanSonicVlanVlan):
    pass


class PatchSonicVlanSonicVlanVlan(SonicVlanSonicVlanVlan):
    pass


class GetSonicVlanSonicVlanVlan(BaseModel):
    sonic_vlan_VLAN: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLAN] = Field(
        None, alias='sonic-vlan:VLAN'
    )


class SonicVlanSonicVlanVlanVlanList(BaseModel):
    sonic_vlan_VLAN_LIST: List[SonicVlanListItem
    ] = Field([], alias='sonic-vlan:VLAN_LIST')


class PutSonicVlanSonicVlanVlanVlanList(SonicVlanSonicVlanVlanVlanList):
    pass


class PatchSonicVlanSonicVlanVlanVlanList(SonicVlanSonicVlanVlanVlanList):
    pass


class GetSonicVlanSonicVlanVlanVlanList(BaseModel):
    sonic_vlan_VLAN_LIST: List[SonicVlanListItem
    ] = Field([], alias='sonic-vlan:VLAN_LIST')


class PostListSonicVlanList(SonicVlanSonicVlanVlanVlanList):
    pass


class PutListSonicVlanSonicVlanVlanVlanList(SonicVlanSonicVlanVlanVlanList):
    pass


class PatchListSonicVlanSonicVlanVlanVlanList(SonicVlanSonicVlanVlanVlanList):
    pass


class PostSonicVlanSonicVlanVlanVlanListVlanid(
    SonicVlanSonicVlanVlanVlanListVlanid,
    SonicVlanSonicVlanVlanVlanListMembers,
    SonicVlanSonicVlanVlanVlanListDhcpServers,
    SonicVlanSonicVlanVlanVlanListMtu,
    SonicVlanSonicVlanVlanVlanListAdminStatus,
):
    pass


class SonicVlanSonicVlanVlanMember(BaseModel):
    sonic_vlan_VLAN_MEMBER: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER] = (
        Field(None, alias='sonic-vlan:VLAN_MEMBER')
    )


class PutSonicVlanSonicVlanVlanMember(SonicVlanSonicVlanVlanMember):
    pass


class PatchSonicVlanSonicVlanVlanMember(SonicVlanSonicVlanVlanMember):
    pass


class GetSonicVlanSonicVlanVlanMember(BaseModel):
    sonic_vlan_VLAN_MEMBER: Optional[SonicVlanSonicVlanSonicvlansonicvlanVLANMEMBER] = (
        Field(None, alias='sonic-vlan:VLAN_MEMBER')
    )


class SonicVlanMemberList(BaseModel):
    sonic_vlan_VLAN_MEMBER_LIST: List[SonicVlanMemberListItem
    ] = Field([], alias='sonic-vlan:VLAN_MEMBER_LIST')


class PutSonicVlanMemberList(
    SonicVlanMemberList
):
    pass


class PatchSonicVlanMemberList(
    SonicVlanMemberList
):
    pass


class GetSonicVlanSonicVlanVlanMemberVlanMemberList(BaseModel):
    sonic_vlan_VLAN_MEMBER_LIST: Optional[
        List[SonicVlanMemberListItem]
    ] = Field(None, alias='sonic-vlan:VLAN_MEMBER_LIST')


class PostListSonicVlanMemberList(
    SonicVlanMemberList
):
    pass


class PutListSonicVlanMemberList(
    SonicVlanMemberList
):
    pass


class PatchListSonicVlanMemberList(
    SonicVlanMemberList
):
    pass


class GetSonicVlanSonicVlanVlanTable(BaseModel):
    sonic_vlan_VLAN_TABLE: Optional[
        GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLE
    ] = Field(None, alias='sonic-vlan:VLAN_TABLE')


class GetSonicVlanSonicVlanVlanTableVlanTableList(BaseModel):
    sonic_vlan_VLAN_TABLE_LIST: Optional[
        List[GetSonicVlanSonicVlanSonicvlansonicvlanVLANTABLEVLANTABLELIST]
    ] = Field(None, alias='sonic-vlan:VLAN_TABLE_LIST')


class GetSonicVlanSonicVlanVlanMemberTable(BaseModel):
    sonic_vlan_VLAN_MEMBER_TABLE: Optional[
        GetSonicVlanSonicVlanSonicvlansonicvlanVLANMEMBERTABLE
    ] = Field(None, alias='sonic-vlan:VLAN_MEMBER_TABLE')


class GetSonicVlanSonicVlanVlanMemberTableVlanMemberTableList(BaseModel):
    sonic_vlan_VLAN_MEMBER_TABLE_LIST: Optional[
        List[SonicVlanMemberListItem]
    ] = Field(None, alias='sonic-vlan:VLAN_MEMBER_TABLE_LIST')


class PostSonicVlanSonicVlanVlan(SonicVlanSonicVlanVlan, SonicVlanSonicVlanVlanMember):
    pass
