# generated by datamodel-codegen:
#   filename:  openapi3_0.yaml
#   timestamp: 2024-05-14T09:01:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class SonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName(BaseModel):
    sonic_interface_vrf_name: Optional[str] = Field(
        None, alias='sonic-interface:vrf_name'
    )


class PutSonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName(
    SonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName
):
    pass


class PatchSonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName(
    SonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName
):
    pass


class GetSonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName(BaseModel):
    sonic_interface_vrf_name: Optional[str] = Field(
        None, alias='sonic-interface:vrf_name'
    )


class SonicInterfaceIpv6UseLinkLocalOnly(Enum):
    enable = 'enable'
    disable = 'disable'


class SonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly(BaseModel):
    sonic_interface_ipv6_use_link_local_only: Optional[
        SonicInterfaceIpv6UseLinkLocalOnly
    ] = Field(None, alias='sonic-interface:ipv6_use_link_local_only')


class PutSonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly(
    SonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly
):
    pass


class PatchSonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly(
    SonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly
):
    pass


class GetSonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly(
    BaseModel
):
    sonic_interface_ipv6_use_link_local_only: Optional[
        SonicInterfaceIpv6UseLinkLocalOnly
    ] = Field(None, alias='sonic-interface:ipv6_use_link_local_only')


class SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary(BaseModel):
    sonic_interface_secondary: Optional[bool] = Field(
        None, alias='sonic-interface:secondary'
    )


class PostSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary
):
    pass


class PutSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary
):
    pass


class PatchSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary
):
    pass


class GetSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrListSecondary(BaseModel):
    sonic_interface_secondary: Optional[bool] = Field(
        None, alias='sonic-interface:secondary'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx(
    BaseModel
):
    sonic_interface_subintfidx: Optional[str] = Field(
        None, alias='sonic-interface:subintfidx'
    )


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx(
    BaseModel
):
    sonic_interface_subintfidx: Optional[str] = Field(
        None, alias='sonic-interface:subintfidx'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname(BaseModel):
    sonic_interface_ifName: Optional[str] = Field(None, alias='sonic-interface:ifName')


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname(
    BaseModel
):
    sonic_interface_ifName: Optional[str] = Field(None, alias='sonic-interface:ifName')


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName(
    BaseModel
):
    sonic_interface_vrf_name: Optional[str] = Field(
        None, alias='sonic-interface:vrf_name'
    )


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName(
    BaseModel
):
    sonic_interface_vrf_name: Optional[str] = Field(
        None, alias='sonic-interface:vrf_name'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan(BaseModel):
    sonic_interface_vlan: Optional[str] = Field(None, alias='sonic-interface:vlan')


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan(
    BaseModel
):
    sonic_interface_vlan: Optional[str] = Field(None, alias='sonic-interface:vlan')


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus(
    BaseModel
):
    sonic_interface_admin_status: Optional[str] = Field(
        None, alias='sonic-interface:admin_status'
    )


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus(
    BaseModel
):
    sonic_interface_admin_status: Optional[str] = Field(
        None, alias='sonic-interface:admin_status'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription(
    BaseModel
):
    sonic_interface_description: Optional[str] = Field(
        None, alias='sonic-interface:description'
    )


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription(
    BaseModel
):
    sonic_interface_description: Optional[str] = Field(
        None, alias='sonic-interface:description'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled(
    BaseModel
):
    sonic_interface_enabled: Optional[str] = Field(
        None, alias='sonic-interface:enabled'
    )


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled(
    BaseModel
):
    sonic_interface_enabled: Optional[str] = Field(
        None, alias='sonic-interface:enabled'
    )


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex(BaseModel):
    sonic_interface_index: Optional[str] = Field(None, alias='sonic-interface:index')


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex(
    BaseModel
):
    sonic_interface_index: Optional[str] = Field(None, alias='sonic-interface:index')


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus(
    BaseModel
):
    sonic_interface_status: Optional[str] = Field(None, alias='sonic-interface:status')


class PostSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus
):
    pass


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrListStatus(
    BaseModel
):
    sonic_interface_status: Optional[str] = Field(None, alias='sonic-interface:status')


class Ipv6UseLinkLocalOnly(Enum):
    enable = 'enable'
    disable = 'disable'


class SonicInterfaceListItem(
    BaseModel
):
    portname: str
    vrf_name: Optional[str] = None
    ipv6_use_link_local_only: Optional[Ipv6UseLinkLocalOnly] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACEIPADDRLIST(
    BaseModel
):
    portname: str
    ip_prefix: str
    secondary: Optional[bool] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACE(BaseModel):
    INTERFACE_LIST: Optional[
        List[
            SonicInterfaceListItem
        ]
    ] = None
    INTERFACE_IPADDR_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACEIPADDRLIST
        ]
    ] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACELIST(
    BaseModel
):
    id: str
    subintfidx: Optional[str] = None
    ifName: Optional[str] = None
    vrf_name: Optional[str] = None
    vlan: Optional[str] = None
    admin_status: Optional[str] = None
    description: Optional[str] = None
    enabled: Optional[str] = None
    index: Optional[str] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACEIPADDRLIST(
    BaseModel
):
    id: str
    ipPrefix: str
    status: Optional[str] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACE(
    BaseModel
):
    VLAN_SUB_INTERFACE_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACELIST
        ]
    ] = None
    VLAN_SUB_INTERFACE_IPADDR_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACEIPADDRLIST
        ]
    ] = None


class SonicInterfaceSonicInterfaceSonicinterfacesonicinterface(BaseModel):
    INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACE
    ] = None
    VLAN_SUB_INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACE
    ] = None


class SonicInterfaceSonicInterface(BaseModel):
    sonic_interface_sonic_interface: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterface
    ] = Field(None, alias='sonic-interface:sonic-interface')


class PostSonicInterfaceSonicInterface(SonicInterfaceSonicInterface):
    pass


class PutSonicInterfaceSonicInterface(SonicInterfaceSonicInterface):
    pass


class PatchSonicInterfaceSonicInterface(SonicInterfaceSonicInterface):
    pass


class GetSonicInterfaceSonicInterface(BaseModel):
    sonic_interface_sonic_interface: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterface
    ] = Field(None, alias='sonic-interface:sonic-interface')


class SonicInterfaceSonicInterfaceInterface(BaseModel):
    sonic_interface_INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACE
    ] = Field(None, alias='sonic-interface:INTERFACE')


class PutSonicInterfaceSonicInterfaceInterface(SonicInterfaceSonicInterfaceInterface):
    pass


class PatchSonicInterfaceSonicInterfaceInterface(SonicInterfaceSonicInterfaceInterface):
    pass


class GetSonicInterfaceSonicInterfaceInterface(BaseModel):
    sonic_interface_INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACE
    ] = Field(None, alias='sonic-interface:INTERFACE')


class SonicInterfaceSonicInterfaceInterfaceInterfaceList(BaseModel):
    sonic_interface_INTERFACE_LIST: List[
            SonicInterfaceListItem
        ] = Field([], alias='sonic-interface:INTERFACE_LIST')


class PutSonicInterfaceSonicInterfaceInterfaceInterfaceList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceList
):
    pass


class PatchSonicInterfaceSonicInterfaceInterfaceInterfaceList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceList
):
    pass


class GetSonicInterfaceSonicInterfaceInterfaceInterfaceList(BaseModel):
    sonic_interface_INTERFACE_LIST: Optional[
        List[
            SonicInterfaceListItem
        ]
    ] = Field(None, alias='sonic-interface:INTERFACE_LIST')


class PutListSonicInterfaceSonicInterfaceInterfaceInterfaceList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceList
):
    pass


class PatchListSonicInterfaceSonicInterfaceInterfaceInterfaceList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceList
):
    pass


class PostSonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName(
    SonicInterfaceSonicInterfaceInterfaceInterfaceListVrfName,
    SonicInterfaceSonicInterfaceInterfaceInterfaceListIpv6UseLinkLocalOnly,
):
    pass


class SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(BaseModel):
    sonic_interface_INTERFACE_IPADDR_LIST: \
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACEIPADDRLIST \
        = Field([], alias='sonic-interface:INTERFACE_IPADDR_LIST')


class PutSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList
):
    pass


class PatchSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList
):
    pass


class GetSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(BaseModel):
    sonic_interface_INTERFACE_IPADDR_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceINTERFACEINTERFACEIPADDRLIST
        ]
    ] = Field(None, alias='sonic-interface:INTERFACE_IPADDR_LIST')


class PutListSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList
):
    pass


class PatchListSonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList
):
    pass


class SonicInterfaceSonicInterfaceVlanSubInterface(BaseModel):
    sonic_interface_VLAN_SUB_INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACE
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE')


class PutSonicInterfaceSonicInterfaceVlanSubInterface(
    SonicInterfaceSonicInterfaceVlanSubInterface
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterface(
    SonicInterfaceSonicInterfaceVlanSubInterface
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterface(BaseModel):
    sonic_interface_VLAN_SUB_INTERFACE: Optional[
        SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACE
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE')


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(BaseModel):
    sonic_interface_VLAN_SUB_INTERFACE_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACELIST
        ]
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE_LIST')


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(BaseModel):
    sonic_interface_VLAN_SUB_INTERFACE_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACELIST
        ]
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE_LIST')


class PutListSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList
):
    pass


class PatchListSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList
):
    pass


class PostSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListSubintfidx,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIfname,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVrfName,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListVlan,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListAdminStatus,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListDescription,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListEnabled,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceListIndex,
):
    pass


class SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(BaseModel):
    sonic_interface_VLAN_SUB_INTERFACE_IPADDR_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACEIPADDRLIST
        ]
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE_IPADDR_LIST')


class PutSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList
):
    pass


class PatchSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList
):
    pass


class GetSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(
    BaseModel
):
    sonic_interface_VLAN_SUB_INTERFACE_IPADDR_LIST: Optional[
        List[
            SonicInterfaceSonicInterfaceSonicinterfacesonicinterfaceVLANSUBINTERFACEVLANSUBINTERFACEIPADDRLIST
        ]
    ] = Field(None, alias='sonic-interface:VLAN_SUB_INTERFACE_IPADDR_LIST')


class PutListSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList
):
    pass


class PatchListSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList
):
    pass


class PostSonicInterfaceSonicInterfaceInterface(
    SonicInterfaceSonicInterfaceInterface, SonicInterfaceSonicInterfaceVlanSubInterface
):
    pass


class PostListSonicInterfaceSonicInterfaceInterfaceInterfaceList(
    SonicInterfaceSonicInterfaceInterfaceInterfaceList,
    SonicInterfaceSonicInterfaceInterfaceInterfaceIpaddrList,
):
    pass


class PostListSonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList(
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceList,
    SonicInterfaceSonicInterfaceVlanSubInterfaceVlanSubInterfaceIpaddrList,
):
    pass


