# generated by datamodel-codegen:
#   filename:  sonic_vrf.yaml
#   timestamp: 2024-05-14T08:56:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class SonicVrfSonicVrfVrfVrfListVni(BaseModel):
    sonic_vrf_vni: Optional[int] = Field(None, alias='sonic-vrf:vni')


class PostSonicVrfSonicVrfVrfVrfListVni(SonicVrfSonicVrfVrfVrfListVni):
    pass


class PutSonicVrfSonicVrfVrfVrfListVni(SonicVrfSonicVrfVrfVrfListVni):
    pass


class PatchSonicVrfSonicVrfVrfVrfListVni(SonicVrfSonicVrfVrfVrfListVni):
    pass


class GetSonicVrfSonicVrfVrfVrfListVni(BaseModel):
    sonic_vrf_vni: Optional[int] = Field(None, alias='sonic-vrf:vni')


class SonicVrfListItem(BaseModel):
    vrf_name: str
    vni: Optional[int] = None


class SonicVrfSonicVrfSonicvrfsonicvrfVRF(BaseModel):
    VRF_LIST: List[SonicVrfListItem] = []


class SonicVrfSonicVrfSonicvrfsonicvrf(BaseModel):
    VRF: SonicVrfSonicVrfSonicvrfsonicvrfVRF = SonicVrfSonicVrfSonicvrfsonicvrfVRF()


class SonicVrfSonicVrf(BaseModel):
    sonic_vrf_sonic_vrf: SonicVrfSonicVrfSonicvrfsonicvrf = Field(
        SonicVrfSonicVrfSonicvrfsonicvrf(), alias='sonic-vrf:sonic-vrf'
    )


class PostSonicVrfSonicVrf(SonicVrfSonicVrf):
    pass


class PutSonicVrfSonicVrf(SonicVrfSonicVrf):
    pass


class PatchSonicVrfSonicVrf(SonicVrfSonicVrf):
    pass


class GetSonicVrfSonicVrf(BaseModel):
    sonic_vrf_sonic_vrf: Optional[SonicVrfSonicVrfSonicvrfsonicvrf] = Field(
        None, alias='sonic-vrf:sonic-vrf'
    )


class SonicVrfSonicVrfVrf(BaseModel):
    sonic_vrf_VRF: Optional[SonicVrfSonicVrfSonicvrfsonicvrfVRF] = Field(
        None, alias='sonic-vrf:VRF'
    )


class PostSonicVrfSonicVrfVrf(SonicVrfSonicVrfVrf):
    pass


class PutSonicVrfSonicVrfVrf(SonicVrfSonicVrfVrf):
    pass


class PatchSonicVrfSonicVrfVrf(SonicVrfSonicVrfVrf):
    pass


class GetSonicVrfSonicVrfVrf(BaseModel):
    sonic_vrf_VRF: Optional[SonicVrfSonicVrfSonicvrfsonicvrfVRF] = Field(
        None, alias='sonic-vrf:VRF'
    )


class SonicVrfSonicVrfVrfVrfList(BaseModel):
    sonic_vrf_VRF_LIST: Optional[List[SonicVrfListItem]] = (
        Field(None, alias='sonic-vrf:VRF_LIST')
    )


class PutSonicVrfSonicVrfVrfVrfList(SonicVrfSonicVrfVrfVrfList):
    pass


class PatchSonicVrfSonicVrfVrfVrfList(SonicVrfSonicVrfVrfVrfList):
    pass


class GetSonicVrfSonicVrfVrfVrfList(BaseModel):
    sonic_vrf_VRF_LIST: Optional[List[SonicVrfListItem]] = (
        Field(None, alias='sonic-vrf:VRF_LIST')
    )


class PostListSonicVrfSonicVrfVrfVrfList(SonicVrfSonicVrfVrfVrfList):
    pass


class PutListSonicVrfSonicVrfVrfVrfList(SonicVrfSonicVrfVrfVrfList):
    pass


class PatchListSonicVrfSonicVrfVrfVrfList(SonicVrfSonicVrfVrfVrfList):
    pass
